services:
  - type: web
    name: musicclub-frontend
    env: static
    buildCommand: cd frontend/docs && npm install && npm run build
    staticPublishPath: ./frontend/docs/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
